/* Auto-generated by genmsg_cpp for file /home/user/ros/ui_alt/msg/src_tf_uialt.msg */
#ifndef UI_ALT_MESSAGE_SRC_TF_UIALT_H
#define UI_ALT_MESSAGE_SRC_TF_UIALT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace ui_alt
{
template <class ContainerAllocator>
struct src_tf_uialt_ {
  typedef src_tf_uialt_<ContainerAllocator> Type;

  src_tf_uialt_()
  : parts()
  , x(0.0)
  , y(0.0)
  , theta(0.0)
  {
  }

  src_tf_uialt_(const ContainerAllocator& _alloc)
  : parts(_alloc)
  , x(0.0)
  , y(0.0)
  , theta(0.0)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _parts_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  parts;

  typedef double _x_type;
  double x;

  typedef double _y_type;
  double y;

  typedef double _theta_type;
  double theta;


  typedef boost::shared_ptr< ::ui_alt::src_tf_uialt_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ui_alt::src_tf_uialt_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct src_tf_uialt
typedef  ::ui_alt::src_tf_uialt_<std::allocator<void> > src_tf_uialt;

typedef boost::shared_ptr< ::ui_alt::src_tf_uialt> src_tf_uialtPtr;
typedef boost::shared_ptr< ::ui_alt::src_tf_uialt const> src_tf_uialtConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ui_alt::src_tf_uialt_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ui_alt::src_tf_uialt_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ui_alt

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ui_alt::src_tf_uialt_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ui_alt::src_tf_uialt_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ui_alt::src_tf_uialt_<ContainerAllocator> > {
  static const char* value() 
  {
    return "729e9dcdb243f5ad949ca0cbb600fd5f";
  }

  static const char* value(const  ::ui_alt::src_tf_uialt_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x729e9dcdb243f5adULL;
  static const uint64_t static_value2 = 0x949ca0cbb600fd5fULL;
};

template<class ContainerAllocator>
struct DataType< ::ui_alt::src_tf_uialt_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ui_alt/src_tf_uialt";
  }

  static const char* value(const  ::ui_alt::src_tf_uialt_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ui_alt::src_tf_uialt_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string parts\n\
float64 x\n\
float64 y\n\
float64 theta\n\
\n\
";
  }

  static const char* value(const  ::ui_alt::src_tf_uialt_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ui_alt::src_tf_uialt_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.parts);
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.theta);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct src_tf_uialt_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ui_alt::src_tf_uialt_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ui_alt::src_tf_uialt_<ContainerAllocator> & v) 
  {
    s << indent << "parts: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.parts);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
  }
};


} // namespace message_operations
} // namespace ros

#endif // UI_ALT_MESSAGE_SRC_TF_UIALT_H

