/* Auto-generated by genmsg_cpp for file /home/user/ros/ui_alt/msg/tf_uialt.msg */
#ifndef UI_ALT_MESSAGE_TF_UIALT_H
#define UI_ALT_MESSAGE_TF_UIALT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ui_alt/src_tf_uialt.h"

namespace ui_alt
{
template <class ContainerAllocator>
struct tf_uialt_ {
  typedef tf_uialt_<ContainerAllocator> Type;

  tf_uialt_()
  : src()
  {
  }

  tf_uialt_(const ContainerAllocator& _alloc)
  : src(_alloc)
  {
  }

  typedef std::vector< ::ui_alt::src_tf_uialt_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::ui_alt::src_tf_uialt_<ContainerAllocator> >::other >  _src_type;
  std::vector< ::ui_alt::src_tf_uialt_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::ui_alt::src_tf_uialt_<ContainerAllocator> >::other >  src;


  typedef boost::shared_ptr< ::ui_alt::tf_uialt_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ui_alt::tf_uialt_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct tf_uialt
typedef  ::ui_alt::tf_uialt_<std::allocator<void> > tf_uialt;

typedef boost::shared_ptr< ::ui_alt::tf_uialt> tf_uialtPtr;
typedef boost::shared_ptr< ::ui_alt::tf_uialt const> tf_uialtConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ui_alt::tf_uialt_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ui_alt::tf_uialt_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ui_alt

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ui_alt::tf_uialt_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ui_alt::tf_uialt_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ui_alt::tf_uialt_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7ffcaccd814bf1cfa9bad231e0d4951e";
  }

  static const char* value(const  ::ui_alt::tf_uialt_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x7ffcaccd814bf1cfULL;
  static const uint64_t static_value2 = 0xa9bad231e0d4951eULL;
};

template<class ContainerAllocator>
struct DataType< ::ui_alt::tf_uialt_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ui_alt/tf_uialt";
  }

  static const char* value(const  ::ui_alt::tf_uialt_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ui_alt::tf_uialt_<ContainerAllocator> > {
  static const char* value() 
  {
    return "src_tf_uialt[] src\n\
================================================================================\n\
MSG: ui_alt/src_tf_uialt\n\
string parts\n\
float64 x\n\
float64 y\n\
float64 theta\n\
\n\
";
  }

  static const char* value(const  ::ui_alt::tf_uialt_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ui_alt::tf_uialt_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.src);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct tf_uialt_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ui_alt::tf_uialt_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ui_alt::tf_uialt_<ContainerAllocator> & v) 
  {
    s << indent << "src[]" << std::endl;
    for (size_t i = 0; i < v.src.size(); ++i)
    {
      s << indent << "  src[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ui_alt::src_tf_uialt_<ContainerAllocator> >::stream(s, indent + "    ", v.src[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // UI_ALT_MESSAGE_TF_UIALT_H

